# Generated by Django 4.2.5 on 2023-10-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecapsule',
            name='published_capsule',
            field=models.BooleanField(default=True),
        ),
    ]
