# Generated by Django 4.2.5 on 2023-10-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0002_timecapsule_published_capsule'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecapsule',
            name='is_public_capsule',
            field=models.BooleanField(default=False),
        ),
    ]
