# Generated by Django 4.2.5 on 2023-10-12 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0003_timecapsule_is_public_capsule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='capsule',
            new_name='timecapsule',
        ),
    ]
