# Generated by Django 4.2.5 on 2023-10-12 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0004_rename_capsule_comment_timecapsule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='timecapsule',
            new_name='time_capsule',
        ),
    ]
